name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make clang

      - name: Configure kernel
        run: |
          cd kernel
          make O=out ARCH=arm64 k65v1_64_bsp_defconfig
          scripts/config --file out/.config --enable CONFIG_KSU
          make O=out ARCH=arm64 olddefconfig

      - name: Build kernel
        run: |
          cd kernel
          make -j$(nproc) O=out ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu-
